[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-lokdown"
version = "1.0.0"
description = "Reusable Django utility library"
readme = "README.md"
authors = [
    { name = "Loknus Labs LLC", email = "loknuslabs@gmail.com" }
]
license = { text = "GPL-3.0-or-later" }
dependencies = [
    "Django>=5.1"
]
requires-python = ">=3.13"

[tool.setuptools.packages.find]
where = ["."]

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py313']
