"""Social provider registry: installed apps and allauth URL name helpers."""

from __future__ import annotations

# Provider id -> Django app providing the allauth provider.
SOCIALAUTH_PROVIDER_APPS: dict[str, str] = {
    "amazon": "allauth.socialaccount.providers.amazon",
    "apple": "allauth.socialaccount.providers.apple",
    "asana": "allauth.socialaccount.providers.asana",
    "atlassian": "allauth.socialaccount.providers.atlassian",
    "auth0": "allauth.socialaccount.providers.auth0",
    "authentiq": "allauth.socialaccount.providers.authentiq",
    "baidu": "allauth.socialaccount.providers.baidu",
    "basecamp": "allauth.socialaccount.providers.basecamp",
    "bitbucket": "allauth.socialaccount.providers.bitbucket",
    "box": "allauth.socialaccount.providers.box",
    "coinbase": "allauth.socialaccount.providers.coinbase",
    "dataporten": "allauth.socialaccount.providers.dataporten",
    "daum": "allauth.socialaccount.providers.daum",
    "digitalocean": "allauth.socialaccount.providers.digitalocean",
    "dingtalk": "allauth.socialaccount.providers.dingtalk",
    "discord": "allauth.socialaccount.providers.discord",
    "douban": "allauth.socialaccount.providers.douban",
    "doximity": "allauth.socialaccount.providers.doximity",
    "draugiem": "allauth.socialaccount.providers.draugiem",
    "dropbox": "allauth.socialaccount.providers.dropbox",
    "dummy": "allauth.socialaccount.providers.dummy",
    "dwolla": "allauth.socialaccount.providers.dwolla",
    "edmodo": "allauth.socialaccount.providers.edmodo",
    "eventbrite": "allauth.socialaccount.providers.eventbrite",
    "eveonline": "allauth.socialaccount.providers.eveonline",
    "evernote": "allauth.socialaccount.providers.evernote",
    "exist": "allauth.socialaccount.providers.exist",
    "facebook": "allauth.socialaccount.providers.facebook",
    "feedly": "allauth.socialaccount.providers.feedly",
    "figma": "allauth.socialaccount.providers.figma",
    "flickr": "allauth.socialaccount.providers.flickr",
    "foursquare": "allauth.socialaccount.providers.foursquare",
    "frontier": "allauth.socialaccount.providers.frontier",
    "fxa": "allauth.socialaccount.providers.fxa",
    "gitea": "allauth.socialaccount.providers.gitea",
    "github": "allauth.socialaccount.providers.github",
    "gitlab": "allauth.socialaccount.providers.gitlab",
    "globus": "allauth.socialaccount.providers.globus",
    "google": "allauth.socialaccount.providers.google",
    "gumroad": "allauth.socialaccount.providers.gumroad",
    "hubspot": "allauth.socialaccount.providers.hubspot",
    "instagram": "allauth.socialaccount.providers.instagram",
    "jupyterhub": "allauth.socialaccount.providers.jupyterhub",
    "kakao": "allauth.socialaccount.providers.kakao",
    "lemonldap": "allauth.socialaccount.providers.lemonldap",
    "line": "allauth.socialaccount.providers.line",
    "linkedin_oauth2": "allauth.socialaccount.providers.linkedin_oauth2",
    "mailchimp": "allauth.socialaccount.providers.mailchimp",
    "mailru": "allauth.socialaccount.providers.mailru",
    "mediawiki": "allauth.socialaccount.providers.mediawiki",
    "meetup": "allauth.socialaccount.providers.meetup",
    "microsoft": "allauth.socialaccount.providers.microsoft",
    "naver": "allauth.socialaccount.providers.naver",
    "nextcloud": "allauth.socialaccount.providers.nextcloud",
    "notion": "allauth.socialaccount.providers.notion",
    "odnoklassniki": "allauth.socialaccount.providers.odnoklassniki",
    "okta": "allauth.socialaccount.providers.okta",
    "openid": "allauth.socialaccount.providers.openid",
    "openid_connect": "allauth.socialaccount.providers.openid_connect",
    "openstreetmap": "allauth.socialaccount.providers.openstreetmap",
    "orcid": "allauth.socialaccount.providers.orcid",
    "patreon": "allauth.socialaccount.providers.patreon",
    "paypal": "allauth.socialaccount.providers.paypal",
    "pinterest": "allauth.socialaccount.providers.pinterest",
    "pocket": "allauth.socialaccount.providers.pocket",
    "questrade": "allauth.socialaccount.providers.questrade",
    "quickbooks": "allauth.socialaccount.providers.quickbooks",
    "reddit": "allauth.socialaccount.providers.reddit",
    "saml": "allauth.socialaccount.providers.saml",
    "salesforce": "allauth.socialaccount.providers.salesforce",
    "sharefile": "allauth.socialaccount.providers.sharefile",
    "shopify": "allauth.socialaccount.providers.shopify",
    "slack": "allauth.socialaccount.providers.slack",
    "snapchat": "allauth.socialaccount.providers.snapchat",
    "soundcloud": "allauth.socialaccount.providers.soundcloud",
    "spotify": "allauth.socialaccount.providers.spotify",
    "stackexchange": "allauth.socialaccount.providers.stackexchange",
    "steam": "allauth.socialaccount.providers.steam",
    "stocktwits": "allauth.socialaccount.providers.stocktwits",
    "strava": "allauth.socialaccount.providers.strava",
    "stripe": "allauth.socialaccount.providers.stripe",
    "telegram": "allauth.socialaccount.providers.telegram",
    "tiktok": "allauth.socialaccount.providers.tiktok",
    "trainingpeaks": "allauth.socialaccount.providers.trainingpeaks",
    "trello": "allauth.socialaccount.providers.trello",
    "tumblr": "allauth.socialaccount.providers.tumblr",
    "twitch": "allauth.socialaccount.providers.twitch",
    "twitter": "allauth.socialaccount.providers.twitter",
    "twitter_oauth2": "allauth.socialaccount.providers.twitter_oauth2",
    "untappd": "allauth.socialaccount.providers.untappd",
    "vimeo": "allauth.socialaccount.providers.vimeo",
    "vimeo_oauth2": "allauth.socialaccount.providers.vimeo_oauth2",
    "vk": "allauth.socialaccount.providers.vk",
    "weibo": "allauth.socialaccount.providers.weibo",
    "weixin": "allauth.socialaccount.providers.weixin",
    "windowslive": "allauth.socialaccount.providers.windowslive",
    "wordpress": "allauth.socialaccount.providers.wordpress",
    "x": "allauth.socialaccount.providers.x",
    "xing": "allauth.socialaccount.providers.xing",
    "yahoo": "allauth.socialaccount.providers.yahoo",
    "yandex": "allauth.socialaccount.providers.yandex",
    "ynab": "allauth.socialaccount.providers.ynab",
    "zoho": "allauth.socialaccount.providers.zoho",
    "zoom": "allauth.socialaccount.providers.zoom",
}

# Non-OAuth2 providers use custom login URL names (default is ``{id}_login``).
CUSTOM_LOGIN_URL_NAMES: dict[str, str] = {
    "dummy": "dummy_login",
    "draugiem": "draugiem_login",
    "openid": "openid_login",
    "openid_connect": "openid_connect_login",
    "saml": "saml_login",
    "steam": "steam_login",
    "telegram": "telegram_login",
}

# URL path segment under ``/accounts/`` (provider slug; usually equals provider id).
CUSTOM_PROVIDER_SLUGS: dict[str, str] = {
    "linkedin_oauth2": "linkedin",
}
