name: Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check code formatting
      run: |
        black --check .
        flake8 .

    - name: Check project
      run: python manage.py check

#    - name: Run tests
#      run: pytest
